
server:
  port: 9580

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bank
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: trainingcqrs

security:
  oauth2:
    resource:
      jwt:
        key-value: springCqrsTrainingKey
