version: '3.7'

services:

  user-cmd-api:
    container_name: user-cmd-api
    image: user-cmd-api:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      
  user-query-api:
    container_name: user-query-api
    image: user-query-api:latest
    restart: always
    ports:
      - "9596:9596"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      
  bankacc-cmd-api:
    container_name: bankacc-cmd-api
    image: bankacc-cmd-api:latest
    restart: always
    ports:
      - "9588:9588"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      
  bankacc-query-api:
    container_name: bankacc-query-api
    image: bankacc-query-api:latest
    restart: always
    ports:
      - "9580:9580"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      
  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    restart: always
    ports:
      - "2023:2023"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      
networks:
  default:
    external:
      name: cqrstraining
